### ISSUE TITLE
Ripple effect looks nice but does not apply to the official material design guide.

### ISSUE THREAD

**Issue by tomscholz** [jossiwolf/js_bottom_tabs#1]
When you look at the example at the bottom of the page you will see that the ripple effect is not supposed to go over all tabs. I accutally don't mind ^^ But then it would apply to the official guide :P
Tab touch target animation: https://material.google.com/components/tabs.html#tabs-specs

**Comment by jossiwolf** [comment]
Actually there's two versions (see https://material.google.com/components/bottom-navigation.html#bottom-navigation-specs). I will add an option to change it if you use white as color for all though later this month.

**Comment by tomscholz** [comment]
@jossiwolf Ahhh I see what you mean! But your script is for a tab! It's not a bottom navigation bar. Just saying ;)

**Comment by jossiwolf** [comment]
@tomscholz It's based on tabs from Materialize - that's why it's called Bottom Tabs.
