### ISSUE TITLE
Does it work with materialize v1?

### ISSUE THREAD

**Issue by judasane** [jossiwolf/js_bottom_tabs#5]
I see this project depends on Jquery, so I wonder if this works without it with the new Materialize version

**Comment by jossiwolf** [comment]
This library depends on jQuery. I didn't really use Materialize for about 1.5years as I'm not active in Web Development anymore, so I haven't checked yet. 

One could surely refactor this library not to use jQuery, but for now, I will leave the library as it is and maybe fork Materialize to add bottom tabs.

As for the new Materialize version, the library should work with it as long as you include jQuery.

Cheers
